// Mocks generated by Mockito 5.4.6 from annotations
// in frontend/test/data/repositories/auth_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:frontend/data/models/anomaly.dart' as _i7;
import 'package:frontend/data/models/auth_session.dart' as _i2;
import 'package:frontend/data/models/dashboard.dart' as _i6;
import 'package:frontend/data/models/extended_finance.dart' as _i12;
import 'package:frontend/data/models/household.dart' as _i4;
import 'package:frontend/data/models/me.dart' as _i3;
import 'package:frontend/data/models/pluggy_connection.dart' as _i5;
import 'package:frontend/data/services/backend_api_service.dart' as _i10;
import 'package:frontend/data/services/secure_token_storage.dart' as _i13;
import 'package:frontend/data/services/supabase_auth_service.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAuthSession_0 extends _i1.SmartFake implements _i2.AuthSession {
  _FakeAuthSession_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMe_1 extends _i1.SmartFake implements _i3.Me {
  _FakeMe_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHousehold_2 extends _i1.SmartFake implements _i4.Household {
  _FakeHousehold_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePluggyConnection_3 extends _i1.SmartFake
    implements _i5.PluggyConnection {
  _FakePluggyConnection_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDashboard_4 extends _i1.SmartFake implements _i6.Dashboard {
  _FakeDashboard_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAnomalySummary_5 extends _i1.SmartFake
    implements _i7.AnomalySummary {
  _FakeAnomalySummary_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SupabaseAuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupabaseAuthService extends _i1.Mock
    implements _i8.SupabaseAuthService {
  @override
  _i9.Future<_i2.AuthSession> signUp(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [email, password]),
            returnValue: _i9.Future<_i2.AuthSession>.value(
              _FakeAuthSession_0(
                this,
                Invocation.method(#signUp, [email, password]),
              ),
            ),
            returnValueForMissingStub: _i9.Future<_i2.AuthSession>.value(
              _FakeAuthSession_0(
                this,
                Invocation.method(#signUp, [email, password]),
              ),
            ),
          )
          as _i9.Future<_i2.AuthSession>);

  @override
  _i9.Future<_i2.AuthSession> signIn(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [email, password]),
            returnValue: _i9.Future<_i2.AuthSession>.value(
              _FakeAuthSession_0(
                this,
                Invocation.method(#signIn, [email, password]),
              ),
            ),
            returnValueForMissingStub: _i9.Future<_i2.AuthSession>.value(
              _FakeAuthSession_0(
                this,
                Invocation.method(#signIn, [email, password]),
              ),
            ),
          )
          as _i9.Future<_i2.AuthSession>);

  @override
  _i9.Future<_i2.AuthSession> refresh(String? refreshToken) =>
      (super.noSuchMethod(
            Invocation.method(#refresh, [refreshToken]),
            returnValue: _i9.Future<_i2.AuthSession>.value(
              _FakeAuthSession_0(
                this,
                Invocation.method(#refresh, [refreshToken]),
              ),
            ),
            returnValueForMissingStub: _i9.Future<_i2.AuthSession>.value(
              _FakeAuthSession_0(
                this,
                Invocation.method(#refresh, [refreshToken]),
              ),
            ),
          )
          as _i9.Future<_i2.AuthSession>);
}

/// A class which mocks [BackendApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBackendApiService extends _i1.Mock implements _i10.BackendApiService {
  @override
  _i9.Future<_i3.Me> getMe(String? accessToken) =>
      (super.noSuchMethod(
            Invocation.method(#getMe, [accessToken]),
            returnValue: _i9.Future<_i3.Me>.value(
              _FakeMe_1(this, Invocation.method(#getMe, [accessToken])),
            ),
            returnValueForMissingStub: _i9.Future<_i3.Me>.value(
              _FakeMe_1(this, Invocation.method(#getMe, [accessToken])),
            ),
          )
          as _i9.Future<_i3.Me>);

  @override
  _i9.Future<List<_i4.Household>> listHouseholds(String? accessToken) =>
      (super.noSuchMethod(
            Invocation.method(#listHouseholds, [accessToken]),
            returnValue: _i9.Future<List<_i4.Household>>.value(
              <_i4.Household>[],
            ),
            returnValueForMissingStub: _i9.Future<List<_i4.Household>>.value(
              <_i4.Household>[],
            ),
          )
          as _i9.Future<List<_i4.Household>>);

  @override
  _i9.Future<_i4.Household> createHousehold(
    String? accessToken,
    String? name,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createHousehold, [accessToken, name]),
            returnValue: _i9.Future<_i4.Household>.value(
              _FakeHousehold_2(
                this,
                Invocation.method(#createHousehold, [accessToken, name]),
              ),
            ),
            returnValueForMissingStub: _i9.Future<_i4.Household>.value(
              _FakeHousehold_2(
                this,
                Invocation.method(#createHousehold, [accessToken, name]),
              ),
            ),
          )
          as _i9.Future<_i4.Household>);

  @override
  _i9.Future<_i4.Household> getHousehold(
    String? accessToken,
    String? householdId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getHousehold, [accessToken, householdId]),
            returnValue: _i9.Future<_i4.Household>.value(
              _FakeHousehold_2(
                this,
                Invocation.method(#getHousehold, [accessToken, householdId]),
              ),
            ),
            returnValueForMissingStub: _i9.Future<_i4.Household>.value(
              _FakeHousehold_2(
                this,
                Invocation.method(#getHousehold, [accessToken, householdId]),
              ),
            ),
          )
          as _i9.Future<_i4.Household>);

  @override
  _i9.Future<String> createConnectToken(
    String? accessToken,
    String? householdId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createConnectToken, [accessToken, householdId]),
            returnValue: _i9.Future<String>.value(
              _i11.dummyValue<String>(
                this,
                Invocation.method(#createConnectToken, [
                  accessToken,
                  householdId,
                ]),
              ),
            ),
            returnValueForMissingStub: _i9.Future<String>.value(
              _i11.dummyValue<String>(
                this,
                Invocation.method(#createConnectToken, [
                  accessToken,
                  householdId,
                ]),
              ),
            ),
          )
          as _i9.Future<String>);

  @override
  _i9.Future<List<_i5.PluggyConnection>> listConnections(
    String? accessToken,
    String? householdId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#listConnections, [accessToken, householdId]),
            returnValue: _i9.Future<List<_i5.PluggyConnection>>.value(
              <_i5.PluggyConnection>[],
            ),
            returnValueForMissingStub:
                _i9.Future<List<_i5.PluggyConnection>>.value(
                  <_i5.PluggyConnection>[],
                ),
          )
          as _i9.Future<List<_i5.PluggyConnection>>);

  @override
  _i9.Future<_i5.PluggyConnection> createConnection(
    String? accessToken,
    String? householdId,
    String? pluggyItemId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createConnection, [
              accessToken,
              householdId,
              pluggyItemId,
            ]),
            returnValue: _i9.Future<_i5.PluggyConnection>.value(
              _FakePluggyConnection_3(
                this,
                Invocation.method(#createConnection, [
                  accessToken,
                  householdId,
                  pluggyItemId,
                ]),
              ),
            ),
            returnValueForMissingStub: _i9.Future<_i5.PluggyConnection>.value(
              _FakePluggyConnection_3(
                this,
                Invocation.method(#createConnection, [
                  accessToken,
                  householdId,
                  pluggyItemId,
                ]),
              ),
            ),
          )
          as _i9.Future<_i5.PluggyConnection>);

  @override
  _i9.Future<_i6.Dashboard> getDashboard(
    String? accessToken,
    String? householdId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getDashboard, [accessToken, householdId]),
            returnValue: _i9.Future<_i6.Dashboard>.value(
              _FakeDashboard_4(
                this,
                Invocation.method(#getDashboard, [accessToken, householdId]),
              ),
            ),
            returnValueForMissingStub: _i9.Future<_i6.Dashboard>.value(
              _FakeDashboard_4(
                this,
                Invocation.method(#getDashboard, [accessToken, householdId]),
              ),
            ),
          )
          as _i9.Future<_i6.Dashboard>);

  @override
  _i9.Future<List<_i12.CreditCardBillSummary>> getCreditCardBills(
    String? accessToken,
    String? householdId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCreditCardBills, [accessToken, householdId]),
            returnValue: _i9.Future<List<_i12.CreditCardBillSummary>>.value(
              <_i12.CreditCardBillSummary>[],
            ),
            returnValueForMissingStub:
                _i9.Future<List<_i12.CreditCardBillSummary>>.value(
                  <_i12.CreditCardBillSummary>[],
                ),
          )
          as _i9.Future<List<_i12.CreditCardBillSummary>>);

  @override
  _i9.Future<List<_i12.InvestmentSummary>> getInvestments(
    String? accessToken,
    String? householdId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getInvestments, [accessToken, householdId]),
            returnValue: _i9.Future<List<_i12.InvestmentSummary>>.value(
              <_i12.InvestmentSummary>[],
            ),
            returnValueForMissingStub:
                _i9.Future<List<_i12.InvestmentSummary>>.value(
                  <_i12.InvestmentSummary>[],
                ),
          )
          as _i9.Future<List<_i12.InvestmentSummary>>);

  @override
  _i9.Future<List<_i12.LoanSummary>> getLoans(
    String? accessToken,
    String? householdId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getLoans, [accessToken, householdId]),
            returnValue: _i9.Future<List<_i12.LoanSummary>>.value(
              <_i12.LoanSummary>[],
            ),
            returnValueForMissingStub: _i9.Future<List<_i12.LoanSummary>>.value(
              <_i12.LoanSummary>[],
            ),
          )
          as _i9.Future<List<_i12.LoanSummary>>);

  @override
  _i9.Future<List<_i12.BalancePoint>> getBalanceHistory(
    String? accessToken,
    String? householdId, {
    int? days = 90,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getBalanceHistory,
              [accessToken, householdId],
              {#days: days},
            ),
            returnValue: _i9.Future<List<_i12.BalancePoint>>.value(
              <_i12.BalancePoint>[],
            ),
            returnValueForMissingStub:
                _i9.Future<List<_i12.BalancePoint>>.value(
                  <_i12.BalancePoint>[],
                ),
          )
          as _i9.Future<List<_i12.BalancePoint>>);

  @override
  _i9.Future<List<_i12.CategoryBreakdownItem>> getCategoryBreakdown(
    String? accessToken,
    String? householdId, {
    int? months = 1,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getCategoryBreakdown,
              [accessToken, householdId],
              {#months: months},
            ),
            returnValue: _i9.Future<List<_i12.CategoryBreakdownItem>>.value(
              <_i12.CategoryBreakdownItem>[],
            ),
            returnValueForMissingStub:
                _i9.Future<List<_i12.CategoryBreakdownItem>>.value(
                  <_i12.CategoryBreakdownItem>[],
                ),
          )
          as _i9.Future<List<_i12.CategoryBreakdownItem>>);

  @override
  _i9.Future<List<_i7.AnomalySummary>> getAnomalies(
    String? accessToken,
    String? householdId, {
    String? statusFilter,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getAnomalies,
              [accessToken, householdId],
              {#statusFilter: statusFilter},
            ),
            returnValue: _i9.Future<List<_i7.AnomalySummary>>.value(
              <_i7.AnomalySummary>[],
            ),
            returnValueForMissingStub:
                _i9.Future<List<_i7.AnomalySummary>>.value(
                  <_i7.AnomalySummary>[],
                ),
          )
          as _i9.Future<List<_i7.AnomalySummary>>);

  @override
  _i9.Future<_i7.AnomalySummary> explainAnomaly(
    String? accessToken,
    String? householdId,
    String? anomalyId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#explainAnomaly, [
              accessToken,
              householdId,
              anomalyId,
            ]),
            returnValue: _i9.Future<_i7.AnomalySummary>.value(
              _FakeAnomalySummary_5(
                this,
                Invocation.method(#explainAnomaly, [
                  accessToken,
                  householdId,
                  anomalyId,
                ]),
              ),
            ),
            returnValueForMissingStub: _i9.Future<_i7.AnomalySummary>.value(
              _FakeAnomalySummary_5(
                this,
                Invocation.method(#explainAnomaly, [
                  accessToken,
                  householdId,
                  anomalyId,
                ]),
              ),
            ),
          )
          as _i9.Future<_i7.AnomalySummary>);

  @override
  _i9.Future<_i7.AnomalySummary> updateAnomalyStatus(
    String? accessToken,
    String? householdId,
    String? anomalyId,
    String? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateAnomalyStatus, [
              accessToken,
              householdId,
              anomalyId,
              status,
            ]),
            returnValue: _i9.Future<_i7.AnomalySummary>.value(
              _FakeAnomalySummary_5(
                this,
                Invocation.method(#updateAnomalyStatus, [
                  accessToken,
                  householdId,
                  anomalyId,
                  status,
                ]),
              ),
            ),
            returnValueForMissingStub: _i9.Future<_i7.AnomalySummary>.value(
              _FakeAnomalySummary_5(
                this,
                Invocation.method(#updateAnomalyStatus, [
                  accessToken,
                  householdId,
                  anomalyId,
                  status,
                ]),
              ),
            ),
          )
          as _i9.Future<_i7.AnomalySummary>);
}

/// A class which mocks [SecureTokenStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecureTokenStorage extends _i1.Mock
    implements _i13.SecureTokenStorage {
  @override
  _i9.Future<void> saveSession(_i2.AuthSession? session) =>
      (super.noSuchMethod(
            Invocation.method(#saveSession, [session]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i2.AuthSession?> readSession() =>
      (super.noSuchMethod(
            Invocation.method(#readSession, []),
            returnValue: _i9.Future<_i2.AuthSession?>.value(),
            returnValueForMissingStub: _i9.Future<_i2.AuthSession?>.value(),
          )
          as _i9.Future<_i2.AuthSession?>);

  @override
  _i9.Future<void> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);
}
