// Mocks generated by Mockito 5.4.6 from annotations
// in frontend/test/data/repositories/connection_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:ui' as _i10;

import 'package:frontend/data/models/anomaly.dart' as _i6;
import 'package:frontend/data/models/dashboard.dart' as _i5;
import 'package:frontend/data/models/extended_finance.dart' as _i12;
import 'package:frontend/data/models/household.dart' as _i3;
import 'package:frontend/data/models/me.dart' as _i2;
import 'package:frontend/data/models/pluggy_connection.dart' as _i4;
import 'package:frontend/data/repositories/auth_repository.dart' as _i7;
import 'package:frontend/data/services/backend_api_service.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMe_0 extends _i1.SmartFake implements _i2.Me {
  _FakeMe_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHousehold_1 extends _i1.SmartFake implements _i3.Household {
  _FakeHousehold_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePluggyConnection_2 extends _i1.SmartFake
    implements _i4.PluggyConnection {
  _FakePluggyConnection_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDashboard_3 extends _i1.SmartFake implements _i5.Dashboard {
  _FakeDashboard_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAnomalySummary_4 extends _i1.SmartFake
    implements _i6.AnomalySummary {
  _FakeAnomalySummary_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i7.AuthRepository {
  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isRestoring =>
      (super.noSuchMethod(
            Invocation.getter(#isRestoring),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i8.Future<void> restoreSession() =>
      (super.noSuchMethod(
            Invocation.method(#restoreSession, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> register(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#register, [email, password]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> login(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<String> getValidAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#getValidAccessToken, []),
            returnValue: _i8.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#getValidAccessToken, []),
              ),
            ),
            returnValueForMissingStub: _i8.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#getValidAccessToken, []),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [BackendApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBackendApiService extends _i1.Mock implements _i11.BackendApiService {
  @override
  _i8.Future<_i2.Me> getMe(String? accessToken) =>
      (super.noSuchMethod(
            Invocation.method(#getMe, [accessToken]),
            returnValue: _i8.Future<_i2.Me>.value(
              _FakeMe_0(this, Invocation.method(#getMe, [accessToken])),
            ),
            returnValueForMissingStub: _i8.Future<_i2.Me>.value(
              _FakeMe_0(this, Invocation.method(#getMe, [accessToken])),
            ),
          )
          as _i8.Future<_i2.Me>);

  @override
  _i8.Future<List<_i3.Household>> listHouseholds(String? accessToken) =>
      (super.noSuchMethod(
            Invocation.method(#listHouseholds, [accessToken]),
            returnValue: _i8.Future<List<_i3.Household>>.value(
              <_i3.Household>[],
            ),
            returnValueForMissingStub: _i8.Future<List<_i3.Household>>.value(
              <_i3.Household>[],
            ),
          )
          as _i8.Future<List<_i3.Household>>);

  @override
  _i8.Future<_i3.Household> createHousehold(
    String? accessToken,
    String? name,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createHousehold, [accessToken, name]),
            returnValue: _i8.Future<_i3.Household>.value(
              _FakeHousehold_1(
                this,
                Invocation.method(#createHousehold, [accessToken, name]),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i3.Household>.value(
              _FakeHousehold_1(
                this,
                Invocation.method(#createHousehold, [accessToken, name]),
              ),
            ),
          )
          as _i8.Future<_i3.Household>);

  @override
  _i8.Future<_i3.Household> getHousehold(
    String? accessToken,
    String? householdId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getHousehold, [accessToken, householdId]),
            returnValue: _i8.Future<_i3.Household>.value(
              _FakeHousehold_1(
                this,
                Invocation.method(#getHousehold, [accessToken, householdId]),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i3.Household>.value(
              _FakeHousehold_1(
                this,
                Invocation.method(#getHousehold, [accessToken, householdId]),
              ),
            ),
          )
          as _i8.Future<_i3.Household>);

  @override
  _i8.Future<String> createConnectToken(
    String? accessToken,
    String? householdId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createConnectToken, [accessToken, householdId]),
            returnValue: _i8.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#createConnectToken, [
                  accessToken,
                  householdId,
                ]),
              ),
            ),
            returnValueForMissingStub: _i8.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#createConnectToken, [
                  accessToken,
                  householdId,
                ]),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<List<_i4.PluggyConnection>> listConnections(
    String? accessToken,
    String? householdId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#listConnections, [accessToken, householdId]),
            returnValue: _i8.Future<List<_i4.PluggyConnection>>.value(
              <_i4.PluggyConnection>[],
            ),
            returnValueForMissingStub:
                _i8.Future<List<_i4.PluggyConnection>>.value(
                  <_i4.PluggyConnection>[],
                ),
          )
          as _i8.Future<List<_i4.PluggyConnection>>);

  @override
  _i8.Future<_i4.PluggyConnection> createConnection(
    String? accessToken,
    String? householdId,
    String? pluggyItemId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createConnection, [
              accessToken,
              householdId,
              pluggyItemId,
            ]),
            returnValue: _i8.Future<_i4.PluggyConnection>.value(
              _FakePluggyConnection_2(
                this,
                Invocation.method(#createConnection, [
                  accessToken,
                  householdId,
                  pluggyItemId,
                ]),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i4.PluggyConnection>.value(
              _FakePluggyConnection_2(
                this,
                Invocation.method(#createConnection, [
                  accessToken,
                  householdId,
                  pluggyItemId,
                ]),
              ),
            ),
          )
          as _i8.Future<_i4.PluggyConnection>);

  @override
  _i8.Future<_i5.Dashboard> getDashboard(
    String? accessToken,
    String? householdId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getDashboard, [accessToken, householdId]),
            returnValue: _i8.Future<_i5.Dashboard>.value(
              _FakeDashboard_3(
                this,
                Invocation.method(#getDashboard, [accessToken, householdId]),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i5.Dashboard>.value(
              _FakeDashboard_3(
                this,
                Invocation.method(#getDashboard, [accessToken, householdId]),
              ),
            ),
          )
          as _i8.Future<_i5.Dashboard>);

  @override
  _i8.Future<List<_i12.CreditCardBillSummary>> getCreditCardBills(
    String? accessToken,
    String? householdId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCreditCardBills, [accessToken, householdId]),
            returnValue: _i8.Future<List<_i12.CreditCardBillSummary>>.value(
              <_i12.CreditCardBillSummary>[],
            ),
            returnValueForMissingStub:
                _i8.Future<List<_i12.CreditCardBillSummary>>.value(
                  <_i12.CreditCardBillSummary>[],
                ),
          )
          as _i8.Future<List<_i12.CreditCardBillSummary>>);

  @override
  _i8.Future<List<_i12.InvestmentSummary>> getInvestments(
    String? accessToken,
    String? householdId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getInvestments, [accessToken, householdId]),
            returnValue: _i8.Future<List<_i12.InvestmentSummary>>.value(
              <_i12.InvestmentSummary>[],
            ),
            returnValueForMissingStub:
                _i8.Future<List<_i12.InvestmentSummary>>.value(
                  <_i12.InvestmentSummary>[],
                ),
          )
          as _i8.Future<List<_i12.InvestmentSummary>>);

  @override
  _i8.Future<List<_i12.LoanSummary>> getLoans(
    String? accessToken,
    String? householdId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getLoans, [accessToken, householdId]),
            returnValue: _i8.Future<List<_i12.LoanSummary>>.value(
              <_i12.LoanSummary>[],
            ),
            returnValueForMissingStub: _i8.Future<List<_i12.LoanSummary>>.value(
              <_i12.LoanSummary>[],
            ),
          )
          as _i8.Future<List<_i12.LoanSummary>>);

  @override
  _i8.Future<List<_i12.BalancePoint>> getBalanceHistory(
    String? accessToken,
    String? householdId, {
    int? days = 90,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getBalanceHistory,
              [accessToken, householdId],
              {#days: days},
            ),
            returnValue: _i8.Future<List<_i12.BalancePoint>>.value(
              <_i12.BalancePoint>[],
            ),
            returnValueForMissingStub:
                _i8.Future<List<_i12.BalancePoint>>.value(
                  <_i12.BalancePoint>[],
                ),
          )
          as _i8.Future<List<_i12.BalancePoint>>);

  @override
  _i8.Future<List<_i12.CategoryBreakdownItem>> getCategoryBreakdown(
    String? accessToken,
    String? householdId, {
    int? months = 1,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getCategoryBreakdown,
              [accessToken, householdId],
              {#months: months},
            ),
            returnValue: _i8.Future<List<_i12.CategoryBreakdownItem>>.value(
              <_i12.CategoryBreakdownItem>[],
            ),
            returnValueForMissingStub:
                _i8.Future<List<_i12.CategoryBreakdownItem>>.value(
                  <_i12.CategoryBreakdownItem>[],
                ),
          )
          as _i8.Future<List<_i12.CategoryBreakdownItem>>);

  @override
  _i8.Future<List<_i6.AnomalySummary>> getAnomalies(
    String? accessToken,
    String? householdId, {
    String? statusFilter,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getAnomalies,
              [accessToken, householdId],
              {#statusFilter: statusFilter},
            ),
            returnValue: _i8.Future<List<_i6.AnomalySummary>>.value(
              <_i6.AnomalySummary>[],
            ),
            returnValueForMissingStub:
                _i8.Future<List<_i6.AnomalySummary>>.value(
                  <_i6.AnomalySummary>[],
                ),
          )
          as _i8.Future<List<_i6.AnomalySummary>>);

  @override
  _i8.Future<_i6.AnomalySummary> explainAnomaly(
    String? accessToken,
    String? householdId,
    String? anomalyId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#explainAnomaly, [
              accessToken,
              householdId,
              anomalyId,
            ]),
            returnValue: _i8.Future<_i6.AnomalySummary>.value(
              _FakeAnomalySummary_4(
                this,
                Invocation.method(#explainAnomaly, [
                  accessToken,
                  householdId,
                  anomalyId,
                ]),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i6.AnomalySummary>.value(
              _FakeAnomalySummary_4(
                this,
                Invocation.method(#explainAnomaly, [
                  accessToken,
                  householdId,
                  anomalyId,
                ]),
              ),
            ),
          )
          as _i8.Future<_i6.AnomalySummary>);

  @override
  _i8.Future<_i6.AnomalySummary> updateAnomalyStatus(
    String? accessToken,
    String? householdId,
    String? anomalyId,
    String? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateAnomalyStatus, [
              accessToken,
              householdId,
              anomalyId,
              status,
            ]),
            returnValue: _i8.Future<_i6.AnomalySummary>.value(
              _FakeAnomalySummary_4(
                this,
                Invocation.method(#updateAnomalyStatus, [
                  accessToken,
                  householdId,
                  anomalyId,
                  status,
                ]),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i6.AnomalySummary>.value(
              _FakeAnomalySummary_4(
                this,
                Invocation.method(#updateAnomalyStatus, [
                  accessToken,
                  householdId,
                  anomalyId,
                  status,
                ]),
              ),
            ),
          )
          as _i8.Future<_i6.AnomalySummary>);
}
