// Mocks generated by Mockito 5.4.6 from annotations
// in frontend/test/data/repositories/dashboard_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;
import 'dart:ui' as _i13;

import 'package:frontend/data/models/anomaly.dart' as _i7;
import 'package:frontend/data/models/assistant_message.dart' as _i8;
import 'package:frontend/data/models/auth_session.dart' as _i11;
import 'package:frontend/data/models/connection_access.dart' as _i16;
import 'package:frontend/data/models/dashboard.dart' as _i6;
import 'package:frontend/data/models/extended_finance.dart' as _i17;
import 'package:frontend/data/models/household.dart' as _i3;
import 'package:frontend/data/models/household_invite.dart' as _i4;
import 'package:frontend/data/models/household_member.dart' as _i15;
import 'package:frontend/data/models/me.dart' as _i2;
import 'package:frontend/data/models/pluggy_connection.dart' as _i5;
import 'package:frontend/data/repositories/auth_repository.dart' as _i9;
import 'package:frontend/data/services/backend_api_service.dart' as _i14;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMe_0 extends _i1.SmartFake implements _i2.Me {
  _FakeMe_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHousehold_1 extends _i1.SmartFake implements _i3.Household {
  _FakeHousehold_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInviteResult_2 extends _i1.SmartFake implements _i4.InviteResult {
  _FakeInviteResult_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInvitePreview_3 extends _i1.SmartFake implements _i4.InvitePreview {
  _FakeInvitePreview_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAcceptInviteResult_4 extends _i1.SmartFake
    implements _i4.AcceptInviteResult {
  _FakeAcceptInviteResult_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePluggyConnection_5 extends _i1.SmartFake
    implements _i5.PluggyConnection {
  _FakePluggyConnection_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDashboard_6 extends _i1.SmartFake implements _i6.Dashboard {
  _FakeDashboard_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAnomalySummary_7 extends _i1.SmartFake
    implements _i7.AnomalySummary {
  _FakeAnomalySummary_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAssistantMessage_8 extends _i1.SmartFake
    implements _i8.AssistantMessage {
  _FakeAssistantMessage_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i9.AuthRepository {
  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isRestoring =>
      (super.noSuchMethod(
            Invocation.getter(#isRestoring),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i10.Future<void> restoreSession() =>
      (super.noSuchMethod(
            Invocation.method(#restoreSession, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> register(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#register, [email, password]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> login(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> applyInviteSession(_i11.AuthSession? session) =>
      (super.noSuchMethod(
            Invocation.method(#applyInviteSession, [session]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> updatePassword(String? newPassword) =>
      (super.noSuchMethod(
            Invocation.method(#updatePassword, [newPassword]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<String> getValidAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#getValidAccessToken, []),
            returnValue: _i10.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#getValidAccessToken, []),
              ),
            ),
            returnValueForMissingStub: _i10.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#getValidAccessToken, []),
              ),
            ),
          )
          as _i10.Future<String>);

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [BackendApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBackendApiService extends _i1.Mock implements _i14.BackendApiService {
  @override
  _i10.Future<_i2.Me> getMe(String? accessToken) =>
      (super.noSuchMethod(
            Invocation.method(#getMe, [accessToken]),
            returnValue: _i10.Future<_i2.Me>.value(
              _FakeMe_0(this, Invocation.method(#getMe, [accessToken])),
            ),
            returnValueForMissingStub: _i10.Future<_i2.Me>.value(
              _FakeMe_0(this, Invocation.method(#getMe, [accessToken])),
            ),
          )
          as _i10.Future<_i2.Me>);

  @override
  _i10.Future<List<_i3.Household>> listHouseholds(String? accessToken) =>
      (super.noSuchMethod(
            Invocation.method(#listHouseholds, [accessToken]),
            returnValue: _i10.Future<List<_i3.Household>>.value(
              <_i3.Household>[],
            ),
            returnValueForMissingStub: _i10.Future<List<_i3.Household>>.value(
              <_i3.Household>[],
            ),
          )
          as _i10.Future<List<_i3.Household>>);

  @override
  _i10.Future<_i3.Household> createHousehold(
    String? accessToken,
    String? name,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createHousehold, [accessToken, name]),
            returnValue: _i10.Future<_i3.Household>.value(
              _FakeHousehold_1(
                this,
                Invocation.method(#createHousehold, [accessToken, name]),
              ),
            ),
            returnValueForMissingStub: _i10.Future<_i3.Household>.value(
              _FakeHousehold_1(
                this,
                Invocation.method(#createHousehold, [accessToken, name]),
              ),
            ),
          )
          as _i10.Future<_i3.Household>);

  @override
  _i10.Future<_i3.Household> getHousehold(
    String? accessToken,
    String? householdId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getHousehold, [accessToken, householdId]),
            returnValue: _i10.Future<_i3.Household>.value(
              _FakeHousehold_1(
                this,
                Invocation.method(#getHousehold, [accessToken, householdId]),
              ),
            ),
            returnValueForMissingStub: _i10.Future<_i3.Household>.value(
              _FakeHousehold_1(
                this,
                Invocation.method(#getHousehold, [accessToken, householdId]),
              ),
            ),
          )
          as _i10.Future<_i3.Household>);

  @override
  _i10.Future<List<_i15.HouseholdMember>> listMembers(
    String? accessToken,
    String? householdId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#listMembers, [accessToken, householdId]),
            returnValue: _i10.Future<List<_i15.HouseholdMember>>.value(
              <_i15.HouseholdMember>[],
            ),
            returnValueForMissingStub:
                _i10.Future<List<_i15.HouseholdMember>>.value(
                  <_i15.HouseholdMember>[],
                ),
          )
          as _i10.Future<List<_i15.HouseholdMember>>);

  @override
  _i10.Future<_i4.InviteResult> inviteMember(
    String? accessToken,
    String? householdId,
    String? email,
    String? role,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#inviteMember, [
              accessToken,
              householdId,
              email,
              role,
            ]),
            returnValue: _i10.Future<_i4.InviteResult>.value(
              _FakeInviteResult_2(
                this,
                Invocation.method(#inviteMember, [
                  accessToken,
                  householdId,
                  email,
                  role,
                ]),
              ),
            ),
            returnValueForMissingStub: _i10.Future<_i4.InviteResult>.value(
              _FakeInviteResult_2(
                this,
                Invocation.method(#inviteMember, [
                  accessToken,
                  householdId,
                  email,
                  role,
                ]),
              ),
            ),
          )
          as _i10.Future<_i4.InviteResult>);

  @override
  _i10.Future<List<_i4.InviteSummary>> listPendingInvites(
    String? accessToken,
    String? householdId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#listPendingInvites, [accessToken, householdId]),
            returnValue: _i10.Future<List<_i4.InviteSummary>>.value(
              <_i4.InviteSummary>[],
            ),
            returnValueForMissingStub:
                _i10.Future<List<_i4.InviteSummary>>.value(
                  <_i4.InviteSummary>[],
                ),
          )
          as _i10.Future<List<_i4.InviteSummary>>);

  @override
  _i10.Future<_i4.InvitePreview> getInvitePreview(String? inviteId) =>
      (super.noSuchMethod(
            Invocation.method(#getInvitePreview, [inviteId]),
            returnValue: _i10.Future<_i4.InvitePreview>.value(
              _FakeInvitePreview_3(
                this,
                Invocation.method(#getInvitePreview, [inviteId]),
              ),
            ),
            returnValueForMissingStub: _i10.Future<_i4.InvitePreview>.value(
              _FakeInvitePreview_3(
                this,
                Invocation.method(#getInvitePreview, [inviteId]),
              ),
            ),
          )
          as _i10.Future<_i4.InvitePreview>);

  @override
  _i10.Future<_i4.AcceptInviteResult> acceptInvite(
    String? accessToken,
    String? inviteId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#acceptInvite, [accessToken, inviteId]),
            returnValue: _i10.Future<_i4.AcceptInviteResult>.value(
              _FakeAcceptInviteResult_4(
                this,
                Invocation.method(#acceptInvite, [accessToken, inviteId]),
              ),
            ),
            returnValueForMissingStub:
                _i10.Future<_i4.AcceptInviteResult>.value(
                  _FakeAcceptInviteResult_4(
                    this,
                    Invocation.method(#acceptInvite, [accessToken, inviteId]),
                  ),
                ),
          )
          as _i10.Future<_i4.AcceptInviteResult>);

  @override
  _i10.Future<List<_i16.ConnectionAccessEntry>> getMemberAccess(
    String? accessToken,
    String? householdId,
    String? memberId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMemberAccess, [
              accessToken,
              householdId,
              memberId,
            ]),
            returnValue: _i10.Future<List<_i16.ConnectionAccessEntry>>.value(
              <_i16.ConnectionAccessEntry>[],
            ),
            returnValueForMissingStub:
                _i10.Future<List<_i16.ConnectionAccessEntry>>.value(
                  <_i16.ConnectionAccessEntry>[],
                ),
          )
          as _i10.Future<List<_i16.ConnectionAccessEntry>>);

  @override
  _i10.Future<List<_i16.ConnectionAccessEntry>> updateMemberAccess(
    String? accessToken,
    String? householdId,
    String? memberId,
    List<String>? connectionIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateMemberAccess, [
              accessToken,
              householdId,
              memberId,
              connectionIds,
            ]),
            returnValue: _i10.Future<List<_i16.ConnectionAccessEntry>>.value(
              <_i16.ConnectionAccessEntry>[],
            ),
            returnValueForMissingStub:
                _i10.Future<List<_i16.ConnectionAccessEntry>>.value(
                  <_i16.ConnectionAccessEntry>[],
                ),
          )
          as _i10.Future<List<_i16.ConnectionAccessEntry>>);

  @override
  _i10.Future<String> createConnectToken(
    String? accessToken,
    String? householdId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createConnectToken, [accessToken, householdId]),
            returnValue: _i10.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#createConnectToken, [
                  accessToken,
                  householdId,
                ]),
              ),
            ),
            returnValueForMissingStub: _i10.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#createConnectToken, [
                  accessToken,
                  householdId,
                ]),
              ),
            ),
          )
          as _i10.Future<String>);

  @override
  _i10.Future<List<_i5.PluggyConnection>> listConnections(
    String? accessToken,
    String? householdId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#listConnections, [accessToken, householdId]),
            returnValue: _i10.Future<List<_i5.PluggyConnection>>.value(
              <_i5.PluggyConnection>[],
            ),
            returnValueForMissingStub:
                _i10.Future<List<_i5.PluggyConnection>>.value(
                  <_i5.PluggyConnection>[],
                ),
          )
          as _i10.Future<List<_i5.PluggyConnection>>);

  @override
  _i10.Future<_i5.PluggyConnection> createConnection(
    String? accessToken,
    String? householdId,
    String? pluggyItemId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createConnection, [
              accessToken,
              householdId,
              pluggyItemId,
            ]),
            returnValue: _i10.Future<_i5.PluggyConnection>.value(
              _FakePluggyConnection_5(
                this,
                Invocation.method(#createConnection, [
                  accessToken,
                  householdId,
                  pluggyItemId,
                ]),
              ),
            ),
            returnValueForMissingStub: _i10.Future<_i5.PluggyConnection>.value(
              _FakePluggyConnection_5(
                this,
                Invocation.method(#createConnection, [
                  accessToken,
                  householdId,
                  pluggyItemId,
                ]),
              ),
            ),
          )
          as _i10.Future<_i5.PluggyConnection>);

  @override
  _i10.Future<_i6.Dashboard> getDashboard(
    String? accessToken,
    String? householdId, {
    DateTime? startDate,
    DateTime? endDate,
    List<String>? memberIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getDashboard,
              [accessToken, householdId],
              {#startDate: startDate, #endDate: endDate, #memberIds: memberIds},
            ),
            returnValue: _i10.Future<_i6.Dashboard>.value(
              _FakeDashboard_6(
                this,
                Invocation.method(
                  #getDashboard,
                  [accessToken, householdId],
                  {
                    #startDate: startDate,
                    #endDate: endDate,
                    #memberIds: memberIds,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i10.Future<_i6.Dashboard>.value(
              _FakeDashboard_6(
                this,
                Invocation.method(
                  #getDashboard,
                  [accessToken, householdId],
                  {
                    #startDate: startDate,
                    #endDate: endDate,
                    #memberIds: memberIds,
                  },
                ),
              ),
            ),
          )
          as _i10.Future<_i6.Dashboard>);

  @override
  _i10.Future<List<_i6.TransactionSummary>> listTransactions(
    String? accessToken,
    String? householdId, {
    DateTime? startDate,
    DateTime? endDate,
    List<String>? memberIds,
    int? limit = 50,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #listTransactions,
              [accessToken, householdId],
              {
                #startDate: startDate,
                #endDate: endDate,
                #memberIds: memberIds,
                #limit: limit,
                #offset: offset,
              },
            ),
            returnValue: _i10.Future<List<_i6.TransactionSummary>>.value(
              <_i6.TransactionSummary>[],
            ),
            returnValueForMissingStub:
                _i10.Future<List<_i6.TransactionSummary>>.value(
                  <_i6.TransactionSummary>[],
                ),
          )
          as _i10.Future<List<_i6.TransactionSummary>>);

  @override
  _i10.Future<List<_i17.CreditCardBillSummary>> getCreditCardBills(
    String? accessToken,
    String? householdId, {
    List<String>? memberIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getCreditCardBills,
              [accessToken, householdId],
              {#memberIds: memberIds},
            ),
            returnValue: _i10.Future<List<_i17.CreditCardBillSummary>>.value(
              <_i17.CreditCardBillSummary>[],
            ),
            returnValueForMissingStub:
                _i10.Future<List<_i17.CreditCardBillSummary>>.value(
                  <_i17.CreditCardBillSummary>[],
                ),
          )
          as _i10.Future<List<_i17.CreditCardBillSummary>>);

  @override
  _i10.Future<List<_i17.InvestmentSummary>> getInvestments(
    String? accessToken,
    String? householdId, {
    List<String>? memberIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getInvestments,
              [accessToken, householdId],
              {#memberIds: memberIds},
            ),
            returnValue: _i10.Future<List<_i17.InvestmentSummary>>.value(
              <_i17.InvestmentSummary>[],
            ),
            returnValueForMissingStub:
                _i10.Future<List<_i17.InvestmentSummary>>.value(
                  <_i17.InvestmentSummary>[],
                ),
          )
          as _i10.Future<List<_i17.InvestmentSummary>>);

  @override
  _i10.Future<List<_i17.LoanSummary>> getLoans(
    String? accessToken,
    String? householdId, {
    List<String>? memberIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getLoans,
              [accessToken, householdId],
              {#memberIds: memberIds},
            ),
            returnValue: _i10.Future<List<_i17.LoanSummary>>.value(
              <_i17.LoanSummary>[],
            ),
            returnValueForMissingStub:
                _i10.Future<List<_i17.LoanSummary>>.value(<_i17.LoanSummary>[]),
          )
          as _i10.Future<List<_i17.LoanSummary>>);

  @override
  _i10.Future<List<_i17.BalancePoint>> getBalanceHistory(
    String? accessToken,
    String? householdId, {
    int? days = 90,
    List<String>? memberIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getBalanceHistory,
              [accessToken, householdId],
              {#days: days, #memberIds: memberIds},
            ),
            returnValue: _i10.Future<List<_i17.BalancePoint>>.value(
              <_i17.BalancePoint>[],
            ),
            returnValueForMissingStub:
                _i10.Future<List<_i17.BalancePoint>>.value(
                  <_i17.BalancePoint>[],
                ),
          )
          as _i10.Future<List<_i17.BalancePoint>>);

  @override
  _i10.Future<List<_i17.CategoryBreakdownItem>> getCategoryBreakdown(
    String? accessToken,
    String? householdId, {
    DateTime? startDate,
    DateTime? endDate,
    List<String>? memberIds,
    bool? comparePrevious = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getCategoryBreakdown,
              [accessToken, householdId],
              {
                #startDate: startDate,
                #endDate: endDate,
                #memberIds: memberIds,
                #comparePrevious: comparePrevious,
              },
            ),
            returnValue: _i10.Future<List<_i17.CategoryBreakdownItem>>.value(
              <_i17.CategoryBreakdownItem>[],
            ),
            returnValueForMissingStub:
                _i10.Future<List<_i17.CategoryBreakdownItem>>.value(
                  <_i17.CategoryBreakdownItem>[],
                ),
          )
          as _i10.Future<List<_i17.CategoryBreakdownItem>>);

  @override
  _i10.Future<List<_i7.AnomalySummary>> getAnomalies(
    String? accessToken,
    String? householdId, {
    String? statusFilter,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getAnomalies,
              [accessToken, householdId],
              {#statusFilter: statusFilter},
            ),
            returnValue: _i10.Future<List<_i7.AnomalySummary>>.value(
              <_i7.AnomalySummary>[],
            ),
            returnValueForMissingStub:
                _i10.Future<List<_i7.AnomalySummary>>.value(
                  <_i7.AnomalySummary>[],
                ),
          )
          as _i10.Future<List<_i7.AnomalySummary>>);

  @override
  _i10.Future<_i7.AnomalySummary> explainAnomaly(
    String? accessToken,
    String? householdId,
    String? anomalyId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#explainAnomaly, [
              accessToken,
              householdId,
              anomalyId,
            ]),
            returnValue: _i10.Future<_i7.AnomalySummary>.value(
              _FakeAnomalySummary_7(
                this,
                Invocation.method(#explainAnomaly, [
                  accessToken,
                  householdId,
                  anomalyId,
                ]),
              ),
            ),
            returnValueForMissingStub: _i10.Future<_i7.AnomalySummary>.value(
              _FakeAnomalySummary_7(
                this,
                Invocation.method(#explainAnomaly, [
                  accessToken,
                  householdId,
                  anomalyId,
                ]),
              ),
            ),
          )
          as _i10.Future<_i7.AnomalySummary>);

  @override
  _i10.Future<_i7.AnomalySummary> updateAnomalyStatus(
    String? accessToken,
    String? householdId,
    String? anomalyId,
    String? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateAnomalyStatus, [
              accessToken,
              householdId,
              anomalyId,
              status,
            ]),
            returnValue: _i10.Future<_i7.AnomalySummary>.value(
              _FakeAnomalySummary_7(
                this,
                Invocation.method(#updateAnomalyStatus, [
                  accessToken,
                  householdId,
                  anomalyId,
                  status,
                ]),
              ),
            ),
            returnValueForMissingStub: _i10.Future<_i7.AnomalySummary>.value(
              _FakeAnomalySummary_7(
                this,
                Invocation.method(#updateAnomalyStatus, [
                  accessToken,
                  householdId,
                  anomalyId,
                  status,
                ]),
              ),
            ),
          )
          as _i10.Future<_i7.AnomalySummary>);

  @override
  _i10.Future<List<_i8.AssistantMessage>> getAssistantMessages(
    String? accessToken,
    String? householdId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAssistantMessages, [
              accessToken,
              householdId,
            ]),
            returnValue: _i10.Future<List<_i8.AssistantMessage>>.value(
              <_i8.AssistantMessage>[],
            ),
            returnValueForMissingStub:
                _i10.Future<List<_i8.AssistantMessage>>.value(
                  <_i8.AssistantMessage>[],
                ),
          )
          as _i10.Future<List<_i8.AssistantMessage>>);

  @override
  _i10.Future<_i8.AssistantMessage> askAssistant(
    String? accessToken,
    String? householdId,
    String? question,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#askAssistant, [
              accessToken,
              householdId,
              question,
            ]),
            returnValue: _i10.Future<_i8.AssistantMessage>.value(
              _FakeAssistantMessage_8(
                this,
                Invocation.method(#askAssistant, [
                  accessToken,
                  householdId,
                  question,
                ]),
              ),
            ),
            returnValueForMissingStub: _i10.Future<_i8.AssistantMessage>.value(
              _FakeAssistantMessage_8(
                this,
                Invocation.method(#askAssistant, [
                  accessToken,
                  householdId,
                  question,
                ]),
              ),
            ),
          )
          as _i10.Future<_i8.AssistantMessage>);
}
