"""add is_transfer to transactions

Revision ID: 644d51535cc7
Revises: d9ddc85ba170
Create Date: 2026-08-11 09:52:26.715785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '644d51535cc7'
down_revision: Union[str, Sequence[str], None] = 'd9ddc85ba170'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('is_transfer', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'is_transfer')
    # ### end Alembic commands ###
