"""add connection access grants

Revision ID: a202922803dc
Revises: 85bcee74fa94
Create Date: 2026-08-05 11:38:34.832984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a202922803dc'
down_revision: Union[str, Sequence[str], None] = '85bcee74fa94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connection_access_grants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_member_id', sa.UUID(), nullable=False),
    sa.Column('pluggy_connection_id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_member_id'], ['household_members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pluggy_connection_id'], ['pluggy_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_member_id', 'pluggy_connection_id', name='uq_connection_access_grants_identity')
    )
    # ### end Alembic commands ###

    # Grandfather existing non-owner members in: seed a grant for every
    # connection already in their household, so nothing changes for anyone
    # today. Only members added after this migration start at zero access.
    op.execute(
        """
        INSERT INTO connection_access_grants (id, household_member_id, pluggy_connection_id, created_at)
        SELECT gen_random_uuid(), hm.id, pc.id, now()
        FROM household_members hm
        JOIN pluggy_connections pc ON pc.household_id = hm.household_id
        WHERE hm.role != 'owner'
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('connection_access_grants')
    # ### end Alembic commands ###
