"""make audit_events household_id nullable with set null on delete

Revision ID: f08e50848c8c
Revises: 4c88ed7857c8
Create Date: 2026-08-06 00:28:48.613665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f08e50848c8c'
down_revision: Union[str, Sequence[str], None] = '4c88ed7857c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_events', 'household_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('audit_events_household_id_fkey', 'audit_events', type_='foreignkey')
    op.create_foreign_key(
        'audit_events_household_id_fkey', 'audit_events', 'households',
        ['household_id'], ['id'], ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('audit_events_household_id_fkey', 'audit_events', type_='foreignkey')
    op.create_foreign_key(
        'audit_events_household_id_fkey', 'audit_events', 'households', ['household_id'], ['id'],
    )
    op.alter_column('audit_events', 'household_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
